# disable blank issue creation
blank_issues_enabled: false

contact_links:
  - name: Android Issues
    url: https://github.com/cengiz-pz/godot-android-share-plugin/issues
    about: Please report Android-related issues via the Android plugin repository.

  - name: iOS Issues
    url: https://github.com/cengiz-pz/godot-ios-share-plugin/issues
    about: Please report iOS-related issues via the iOS plugin repository.

